#!/usr/bin/env python3
"""Fast, dependency-free structural checks for this plugin repository."""

from __future__ import annotations

import json
import re
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parent.parent
SKILLS = ROOT / "skills"
FRONTMATTER = re.compile(r"\A---\s*\n(.*?)\n---\s*\n", re.DOTALL)
NAME = re.compile(r"^name:\s*([a-z0-9-]+)\s*$", re.MULTILINE)
DESCRIPTION = re.compile(r"^description:\s*(.+)\s*$", re.MULTILINE)
GENERATED_MARKER = "<!-- Generated by Project Agent Toolkit; edit .agent-governance.json instead. -->"


def fail(errors: list[str], message: str) -> None:
    errors.append(message)


def check_manifest(errors: list[str]) -> None:
    path = ROOT / ".codex-plugin" / "plugin.json"
    try:
        manifest = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as exc:
        fail(errors, f"{path.relative_to(ROOT)}: invalid manifest: {exc}")
        return
    for field in ("name", "version", "description", "author", "skills", "interface"):
        if field not in manifest:
            fail(errors, f"{path.relative_to(ROOT)}: missing field {field}")
    if manifest.get("skills") != "./skills/":
        fail(errors, f"{path.relative_to(ROOT)}: skills must resolve to ./skills/")
    if not re.fullmatch(r"\d+\.\d+\.\d+(?:[-+][0-9A-Za-z.-]+)?", str(manifest.get("version", ""))):
        fail(errors, f"{path.relative_to(ROOT)}: version must be semantic")


def check_skills(errors: list[str]) -> None:
    names: set[str] = set()
    for directory in sorted(path for path in SKILLS.iterdir() if path.is_dir()):
        skill = directory / "SKILL.md"
        if not skill.exists():
            fail(errors, f"{directory.relative_to(ROOT)}: missing SKILL.md")
            continue
        text = skill.read_text(encoding="utf-8")
        match = FRONTMATTER.match(text)
        if not match:
            fail(errors, f"{skill.relative_to(ROOT)}: invalid frontmatter")
            continue
        frontmatter = match.group(1)
        name_match = NAME.search(frontmatter)
        description_match = DESCRIPTION.search(frontmatter)
        if not name_match:
            fail(errors, f"{skill.relative_to(ROOT)}: missing normalized name")
        else:
            name = name_match.group(1)
            if name != directory.name:
                fail(errors, f"{skill.relative_to(ROOT)}: name must match directory")
            if name in names:
                fail(errors, f"{skill.relative_to(ROOT)}: duplicate skill name {name}")
            names.add(name)
        if not description_match or len(description_match.group(1).strip()) < 80:
            fail(errors, f"{skill.relative_to(ROOT)}: description must explain triggers")
        if "[TODO" in text or "TODO:" in text:
            fail(errors, f"{skill.relative_to(ROOT)}: scaffold TODO remains")
        if len(text.splitlines()) > 500:
            fail(errors, f"{skill.relative_to(ROOT)}: exceeds 500-line context budget")

        agent = directory / "agents" / "openai.yaml"
        if not agent.exists():
            fail(errors, f"{directory.relative_to(ROOT)}: missing agents/openai.yaml")
        else:
            agent_text = agent.read_text(encoding="utf-8")
            if f"$%s" % directory.name not in agent_text:
                fail(errors, f"{agent.relative_to(ROOT)}: default_prompt must name the skill")


def check_templates(errors: list[str]) -> None:
    template_root = ROOT / "assets" / "templates"
    required = [
        "minimal/.agent-governance.json",
        "minimal/AGENTS.md",
        "minimal/.github/copilot-instructions.md",
        "minimal/RULES.md",
        "minimal/docs/ARCHITECTURE.md",
        "minimal/docs/WORKFLOW.md",
        "minimal/PROGRESS.md",
    ]
    for relative in required:
        if not (template_root / relative).is_file():
            fail(errors, f"assets/templates/{relative}: required template missing")

    for path in template_root.rglob("*"):
        if not path.is_file():
            continue
        text = path.read_text(encoding="utf-8")
        if re.search(r"^\s*model(?:_reasoning_effort)?\s*=", text, re.MULTILINE):
            fail(errors, f"{path.relative_to(ROOT)}: templates must not select a model")
        if "[TODO" in text or "TODO:" in text:
            fail(errors, f"{path.relative_to(ROOT)}: template TODO remains")


def check_governance_contract(errors: list[str]) -> None:
    path = ROOT / ".agent-governance.json"
    try:
        config = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as exc:
        fail(errors, f"{path.relative_to(ROOT)}: invalid governance config: {exc}")
        return
    if config.get("version") != 2:
        fail(errors, f"{path.relative_to(ROOT)}: schema version must be 2")

    outputs = config.get("adapters", {}).get("outputs", [])
    expected = {
        ("agents", "AGENTS.md"),
        ("copilot", ".github/copilot-instructions.md"),
    }
    actual = {
        (item.get("kind"), item.get("path"))
        for item in outputs
        if isinstance(item, dict)
    }
    if not expected.issubset(actual):
        fail(errors, f"{path.relative_to(ROOT)}: required managed adapters are missing")
    for _, relative in expected:
        adapter = ROOT / relative
        if not adapter.is_file():
            fail(errors, f"{relative}: managed adapter is missing")
            continue
        if GENERATED_MARKER not in adapter.read_text(encoding="utf-8"):
            fail(errors, f"{relative}: managed adapter marker is missing")

    if not config.get("route_tests"):
        fail(errors, f"{path.relative_to(ROOT)}: route_tests must not be empty")
    validation = config.get("validation", {})
    if not validation.get("profiles"):
        fail(errors, f"{path.relative_to(ROOT)}: validation profiles must not be empty")
    evidence = config.get("evidence", {})
    if not isinstance(evidence.get("directory"), str) or not evidence["directory"]:
        fail(errors, f"{path.relative_to(ROOT)}: evidence directory is required")


def main() -> int:
    errors: list[str] = []
    check_manifest(errors)
    check_skills(errors)
    check_templates(errors)
    check_governance_contract(errors)
    if errors:
        print("check-plugin: FAIL", file=sys.stderr)
        for error in errors:
            print(f"  {error}", file=sys.stderr)
        return 1
    print("check-plugin: OK")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
