#!/usr/bin/env python3
"""Fast, dependency-free structural checks for this plugin repository."""

from __future__ import annotations

import json
import re
import sys
import tomllib
from pathlib import Path


ROOT = Path(__file__).resolve().parent.parent
PLUGIN_ROOT = ROOT / "plugins" / "project-agent-toolkit"
SKILLS = PLUGIN_ROOT / "skills"
FRONTMATTER = re.compile(r"\A---\s*\n(.*?)\n---\s*\n", re.DOTALL)
NAME = re.compile(r"^name:\s*([a-z0-9-]+)\s*$", re.MULTILINE)
DESCRIPTION = re.compile(r"^description:\s*(.+)\s*$", re.MULTILINE)
GENERATED_MARKER = "<!-- Generated by Project Agent Toolkit; edit .agent-governance.json instead. -->"


def fail(errors: list[str], message: str) -> None:
    errors.append(message)


def check_manifest(errors: list[str]) -> None:
    path = PLUGIN_ROOT / ".codex-plugin" / "plugin.json"
    try:
        manifest = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as exc:
        fail(errors, f"{path.relative_to(ROOT)}: invalid manifest: {exc}")
        return
    for field in ("name", "version", "description", "author", "skills", "interface"):
        if field not in manifest:
            fail(errors, f"{path.relative_to(ROOT)}: missing field {field}")
    if manifest.get("skills") != "./skills/":
        fail(errors, f"{path.relative_to(ROOT)}: skills must resolve to ./skills/")
    if not re.fullmatch(r"\d+\.\d+\.\d+(?:[-+][0-9A-Za-z.-]+)?", str(manifest.get("version", ""))):
        fail(errors, f"{path.relative_to(ROOT)}: version must be semantic")


def check_skills(errors: list[str]) -> None:
    names: set[str] = set()
    for directory in sorted(path for path in SKILLS.iterdir() if path.is_dir()):
        skill = directory / "SKILL.md"
        if not skill.exists():
            fail(errors, f"{directory.relative_to(ROOT)}: missing SKILL.md")
            continue
        text = skill.read_text(encoding="utf-8")
        match = FRONTMATTER.match(text)
        if not match:
            fail(errors, f"{skill.relative_to(ROOT)}: invalid frontmatter")
            continue
        frontmatter = match.group(1)
        name_match = NAME.search(frontmatter)
        description_match = DESCRIPTION.search(frontmatter)
        if not name_match:
            fail(errors, f"{skill.relative_to(ROOT)}: missing normalized name")
        else:
            name = name_match.group(1)
            if name != directory.name:
                fail(errors, f"{skill.relative_to(ROOT)}: name must match directory")
            if name in names:
                fail(errors, f"{skill.relative_to(ROOT)}: duplicate skill name {name}")
            names.add(name)
        if not description_match or len(description_match.group(1).strip()) < 80:
            fail(errors, f"{skill.relative_to(ROOT)}: description must explain triggers")
        if "[TODO" in text or "TODO:" in text:
            fail(errors, f"{skill.relative_to(ROOT)}: scaffold TODO remains")
        if len(text.splitlines()) > 500:
            fail(errors, f"{skill.relative_to(ROOT)}: exceeds 500-line context budget")

        agent = directory / "agents" / "openai.yaml"
        if not agent.exists():
            fail(errors, f"{directory.relative_to(ROOT)}: missing agents/openai.yaml")
        else:
            agent_text = agent.read_text(encoding="utf-8")
            if f"$%s" % directory.name not in agent_text:
                fail(errors, f"{agent.relative_to(ROOT)}: default_prompt must name the skill")


def check_templates(errors: list[str]) -> None:
    template_root = PLUGIN_ROOT / "assets" / "templates"
    required = [
        "minimal/.agent-governance.json",
        "minimal/AGENTS.md",
        "minimal/.github/copilot-instructions.md",
        "minimal/RULES.md",
        "minimal/docs/ARCHITECTURE.md",
        "minimal/docs/WORKFLOW.md",
        "minimal/PROGRESS.md",
        "full/.codex/config.toml",
        "full/.codex/agents/architect.toml",
        "full/.codex/agents/verifier.toml",
        "full/.codex/agents/worker.toml",
        "full/.github/prompts/handoff.prompt.md",
        "full/.github/prompts/resume.prompt.md",
        "full/.github/prompts/review.prompt.md",
    ]
    for relative in required:
        if not (template_root / relative).is_file():
            fail(errors, f"assets/templates/{relative}: required template missing")

    config_path = template_root / "minimal" / ".agent-governance.json"
    try:
        template_config = json.loads(config_path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as exc:
        fail(errors, f"{config_path.relative_to(ROOT)}: invalid template config: {exc}")
    else:
        if template_config.get("version") != 4:
            fail(errors, f"{config_path.relative_to(ROOT)}: schema version must be 4")
        visual = template_config.get("visual_validation", {})
        for required_field in (
            "routes",
            "artifact_min_count",
            "min_review_checks",
            "artifact_max_age_seconds",
            "require_review",
            "require_surface",
        ):
            if required_field not in visual:
                fail(
                    errors,
                    (
                        f"{config_path.relative_to(ROOT)}: visual_validation "
                        f"missing {required_field}"
                    ),
                )

    full_config_path = template_root / "full" / ".codex" / "config.toml"
    try:
        full_config = tomllib.loads(
            full_config_path.read_text(encoding="utf-8")
        )
    except (OSError, tomllib.TOMLDecodeError) as exc:
        fail(
            errors,
            f"{full_config_path.relative_to(ROOT)}: invalid TOML: {exc}",
        )
    else:
        if full_config.get("agents") != {
            "max_concurrent_threads_per_session": 4,
            "interrupt_message": True,
        }:
            fail(
                errors,
                (
                    f"{full_config_path.relative_to(ROOT)}: agents must use "
                    "the current bounded-thread configuration"
                ),
            )

    role_names: set[str] = set()
    for role_path in sorted(
        (template_root / "full" / ".codex" / "agents").glob("*.toml")
    ):
        try:
            role = tomllib.loads(role_path.read_text(encoding="utf-8"))
        except (OSError, tomllib.TOMLDecodeError) as exc:
            fail(
                errors,
                f"{role_path.relative_to(ROOT)}: invalid TOML: {exc}",
            )
            continue
        for field in ("name", "description", "developer_instructions"):
            value = role.get(field)
            if not isinstance(value, str) or not value.strip():
                fail(
                    errors,
                    (
                        f"{role_path.relative_to(ROOT)}: missing non-empty "
                        f"{field}"
                    ),
                )
        name = role.get("name")
        if isinstance(name, str):
            if name in role_names:
                fail(
                    errors,
                    (
                        f"{role_path.relative_to(ROOT)}: duplicate role name "
                        f"{name}"
                    ),
                )
            role_names.add(name)
    if role_names != {"architect", "verifier", "worker"}:
        fail(
            errors,
            "assets/templates/full/.codex/agents: expected three generic roles",
        )

    for path in template_root.rglob("*"):
        if not path.is_file():
            continue
        text = path.read_text(encoding="utf-8")
        if re.search(r"^\s*model(?:_reasoning_effort)?\s*=", text, re.MULTILINE):
            fail(errors, f"{path.relative_to(ROOT)}: templates must not select a model")
        if "[TODO" in text or "TODO:" in text:
            fail(errors, f"{path.relative_to(ROOT)}: template TODO remains")


def check_marketplace(errors: list[str]) -> None:
    path = ROOT / ".agents" / "plugins" / "marketplace.json"
    try:
        marketplace = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as exc:
        fail(errors, f"{path.relative_to(ROOT)}: invalid marketplace: {exc}")
        return

    if marketplace.get("name") != "project-agent-toolkit":
        fail(errors, f"{path.relative_to(ROOT)}: unexpected marketplace name")
    entries = marketplace.get("plugins")
    if not isinstance(entries, list):
        fail(errors, f"{path.relative_to(ROOT)}: plugins must be a list")
        return
    matching = [
        entry
        for entry in entries
        if isinstance(entry, dict) and entry.get("name") == "project-agent-toolkit"
    ]
    if len(matching) != 1:
        fail(errors, f"{path.relative_to(ROOT)}: expected exactly one toolkit entry")
        return
    source = matching[0].get("source")
    if source != {
        "source": "local",
        "path": "./plugins/project-agent-toolkit",
    }:
        fail(errors, f"{path.relative_to(ROOT)}: toolkit source path is invalid")
    if not (PLUGIN_ROOT / ".codex-plugin" / "plugin.json").is_file():
        fail(errors, f"{path.relative_to(ROOT)}: marketplace source has no manifest")


def check_governance_contract(errors: list[str]) -> None:
    path = ROOT / ".agent-governance.json"
    try:
        config = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as exc:
        fail(errors, f"{path.relative_to(ROOT)}: invalid governance config: {exc}")
        return
    if config.get("version") != 4:
        fail(errors, f"{path.relative_to(ROOT)}: schema version must be 4")

    outputs = config.get("adapters", {}).get("outputs", [])
    expected = {
        ("agents", "AGENTS.md"),
        ("copilot", ".github/copilot-instructions.md"),
    }
    actual = {
        (item.get("kind"), item.get("path"))
        for item in outputs
        if isinstance(item, dict)
    }
    if not expected.issubset(actual):
        fail(errors, f"{path.relative_to(ROOT)}: required managed adapters are missing")
    for _, relative in expected:
        adapter = ROOT / relative
        if not adapter.is_file():
            fail(errors, f"{relative}: managed adapter is missing")
            continue
        if GENERATED_MARKER not in adapter.read_text(encoding="utf-8"):
            fail(errors, f"{relative}: managed adapter marker is missing")

    if not config.get("route_tests"):
        fail(errors, f"{path.relative_to(ROOT)}: route_tests must not be empty")
    validation = config.get("validation", {})
    if not validation.get("profiles"):
        fail(errors, f"{path.relative_to(ROOT)}: validation profiles must not be empty")
    evidence = config.get("evidence", {})
    if not isinstance(evidence.get("directory"), str) or not evidence["directory"]:
        fail(errors, f"{path.relative_to(ROOT)}: evidence directory is required")


def main() -> int:
    errors: list[str] = []
    check_marketplace(errors)
    check_manifest(errors)
    check_skills(errors)
    check_templates(errors)
    check_governance_contract(errors)
    if errors:
        print("check-plugin: FAIL", file=sys.stderr)
        for error in errors:
            print(f"  {error}", file=sys.stderr)
        return 1
    print("check-plugin: OK")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
