#!/usr/bin/env python3
"""Bootstrap, route, and audit project-neutral agent governance."""

from __future__ import annotations

import argparse
import fnmatch
import hashlib
import json
import re
import shutil
import subprocess
import sys
import time
from dataclasses import asdict, dataclass
from datetime import datetime, timezone
from pathlib import Path, PurePosixPath
from typing import Any, Iterable
from urllib.parse import unquote


CONFIG_NAME = ".agent-governance.json"
CURRENT_VERSION = 3
PLUGIN_ROOT = Path(__file__).resolve().parent.parent
TEMPLATE_ROOT = PLUGIN_ROOT / "assets" / "templates"
MARKDOWN_LINK = re.compile(r"!?\[[^\]\n]+]\(([^)\n]+)\)")
GENERATED_MARKER = "<!-- Generated by Project Agent Toolkit; edit .agent-governance.json instead. -->"


@dataclass(frozen=True)
class Finding:
    severity: str
    code: str
    message: str
    path: str | None = None


def project_path(root: Path, relative: str) -> Path:
    candidate = (root / relative).resolve()
    try:
        candidate.relative_to(root.resolve())
    except ValueError as exc:
        raise ValueError(f"path escapes project root: {relative}") from exc
    return candidate


def posix(relative: str | Path) -> str:
    return str(relative).replace("\\", "/")


def read_json(path: Path) -> dict[str, Any]:
    payload = json.loads(path.read_text(encoding="utf-8"))
    if not isinstance(payload, dict):
        raise ValueError(f"{path} must contain a JSON object")
    return payload


def line_count(path: Path) -> int:
    return len(path.read_text(encoding="utf-8").splitlines())


def iter_template_files(profile: str) -> Iterable[tuple[Path, Path]]:
    for source_root in (TEMPLATE_ROOT / "minimal", TEMPLATE_ROOT / profile):
        if not source_root.exists():
            continue
        for source in sorted(p for p in source_root.rglob("*") if p.is_file()):
            yield source, source.relative_to(source_root)


def initialize(root: Path, profile: str, force: bool) -> int:
    root.mkdir(parents=True, exist_ok=True)
    written: list[str] = []
    preserved: list[str] = []
    seen: set[str] = set()
    for source, relative in iter_template_files(profile):
        key = posix(relative)
        if key in seen:
            continue
        seen.add(key)
        target = root / relative
        if target.exists() and not force:
            preserved.append(key)
            continue
        target.parent.mkdir(parents=True, exist_ok=True)
        shutil.copyfile(source, target)
        written.append(key)

    print(f"Initialized governance in {root}")
    if written:
        print("Created:")
        for path in written:
            print(f"  {path}")
    if preserved:
        print("Preserved existing files:")
        for path in preserved:
            print(f"  {path}")
    print("Next: customize .agent-governance.json, then run `governance.py audit`.")
    return 0


def load_config(root: Path) -> tuple[dict[str, Any] | None, list[Finding]]:
    path = root / CONFIG_NAME
    if not path.exists():
        return None, [
            Finding(
                "error",
                "config.missing",
                f"{CONFIG_NAME} is missing; run the bootstrap command first",
                CONFIG_NAME,
            )
        ]
    try:
        config = read_json(path)
    except (OSError, ValueError, json.JSONDecodeError) as exc:
        return None, [Finding("error", "config.invalid", str(exc), CONFIG_NAME)]
    return config, []


def markdown_link_findings(root: Path, relative: str) -> list[Finding]:
    path = project_path(root, relative)
    findings: list[Finding] = []
    if not path.exists() or path.suffix.lower() != ".md":
        return findings
    text = path.read_text(encoding="utf-8")
    for raw_target in MARKDOWN_LINK.findall(text):
        target = raw_target.strip().strip("<>")
        target = target.split(maxsplit=1)[0].strip("\"'")
        if not target or target.startswith(("#", "mailto:")):
            continue
        if re.match(r"^[a-zA-Z][a-zA-Z0-9+.-]*:", target):
            continue
        target = unquote(target.split("#", 1)[0])
        if not target:
            continue
        resolved = (path.parent / target).resolve()
        try:
            resolved.relative_to(root.resolve())
        except ValueError:
            findings.append(
                Finding(
                    "error",
                    "link.escapes-root",
                    f"link target escapes project root: {raw_target}",
                    relative,
                )
            )
            continue
        if not resolved.exists():
            findings.append(
                Finding(
                    "error",
                    "link.missing",
                    f"link target does not exist: {raw_target}",
                    relative,
                )
            )
    return findings


def normalized_paragraphs(path: Path, minimum: int) -> dict[str, str]:
    text = path.read_text(encoding="utf-8")
    result: dict[str, str] = {}
    for paragraph in re.split(r"\n\s*\n", text):
        cleaned = " ".join(
            line.strip()
            for line in paragraph.splitlines()
            if line.strip() and not line.lstrip().startswith(("#", "```"))
        )
        normalized = re.sub(r"\s+", " ", cleaned).strip().lower()
        if len(normalized) >= minimum:
            result[normalized] = cleaned
    return result


def matches_allowed(path: str, patterns: list[str]) -> bool:
    normalized = posix(path)
    pure = PurePosixPath(normalized)
    return any(
        fnmatch.fnmatchcase(normalized, pattern) or pure.match(pattern)
        for pattern in patterns
    )


def audit(root: Path) -> tuple[list[Finding], dict[str, Any]]:
    config, findings = load_config(root)
    metrics: dict[str, Any] = {
        "root": str(root),
        "entrypoint_lines": {},
        "always_loaded_chars": 0,
        "authority_count": 0,
        "route_count": 0,
        "development_interface_count": 0,
    }
    if config is None:
        return findings, metrics

    if config.get("version") != CURRENT_VERSION:
        findings.append(
            Finding(
                "error",
                "config.version",
                (
                    f"configuration version must be {CURRENT_VERSION}; "
                    "run `governance.py upgrade`"
                ),
                CONFIG_NAME,
            )
        )

    limits = config.get("limits", {})
    if not isinstance(limits, dict):
        findings.append(Finding("error", "config.limits", "limits must be an object", CONFIG_NAME))
        limits = {}
    entrypoint_limit = int(limits.get("entrypoint_max_lines", 120))
    context_limit = int(limits.get("always_loaded_max_chars", 30000))
    duplicate_min = int(limits.get("duplicate_paragraph_min_chars", 180))

    entrypoints = config.get("entrypoints", [])
    if not isinstance(entrypoints, list) or not all(isinstance(x, str) for x in entrypoints):
        findings.append(
            Finding("error", "config.entrypoints", "entrypoints must be an array of paths", CONFIG_NAME)
        )
        entrypoints = []
    if len(set(entrypoints)) != len(entrypoints):
        findings.append(
            Finding("error", "entrypoint.duplicate", "entrypoints contain duplicates", CONFIG_NAME)
        )

    authorities_raw = config.get("authorities", [])
    if not isinstance(authorities_raw, list):
        findings.append(
            Finding("error", "config.authorities", "authorities must be an array", CONFIG_NAME)
        )
        authorities_raw = []

    authorities: dict[str, dict[str, Any]] = {}
    authority_paths: list[str] = []
    for item in authorities_raw:
        if not isinstance(item, dict):
            findings.append(
                Finding("error", "authority.invalid", "each authority must be an object", CONFIG_NAME)
            )
            continue
        identifier = item.get("id")
        relative = item.get("path")
        if not isinstance(identifier, str) or not identifier:
            findings.append(
                Finding("error", "authority.id", "authority id must be non-empty", CONFIG_NAME)
            )
            continue
        if identifier in authorities:
            findings.append(
                Finding("error", "authority.duplicate", f"duplicate authority id: {identifier}", CONFIG_NAME)
            )
            continue
        if not isinstance(relative, str) or not relative:
            findings.append(
                Finding(
                    "error",
                    "authority.path",
                    f"authority {identifier} has no valid path",
                    CONFIG_NAME,
                )
            )
            continue
        authorities[identifier] = item
        authority_paths.append(relative)

    metrics["authority_count"] = len(authorities)
    checked_docs: list[str] = []
    always_paths: list[str] = []
    for relative in list(entrypoints) + authority_paths:
        if relative in checked_docs:
            continue
        checked_docs.append(relative)
        try:
            path = project_path(root, relative)
        except ValueError as exc:
            findings.append(Finding("error", "path.escapes-root", str(exc), relative))
            continue
        if not path.exists():
            findings.append(
                Finding("error", "document.missing", "configured document does not exist", relative)
            )
            continue
        if not path.is_file():
            findings.append(
                Finding("error", "document.not-file", "configured document is not a file", relative)
            )
            continue
        findings.extend(markdown_link_findings(root, relative))

    for relative in entrypoints:
        path = root / relative
        if not path.is_file():
            continue
        lines = line_count(path)
        metrics["entrypoint_lines"][relative] = lines
        always_paths.append(relative)
        if lines > entrypoint_limit:
            findings.append(
                Finding(
                    "warning",
                    "entrypoint.too-large",
                    f"{lines} lines exceeds configured limit {entrypoint_limit}",
                    relative,
                )
            )

    for authority in authorities.values():
        if authority.get("always") is True:
            always_paths.append(str(authority["path"]))

    always_paths = list(dict.fromkeys(always_paths))
    metrics["always_loaded_chars"] = sum(
        (root / relative).stat().st_size
        for relative in always_paths
        if (root / relative).is_file()
    )
    metrics["always_loaded_documents"] = always_paths
    if metrics["always_loaded_chars"] > context_limit:
        findings.append(
            Finding(
                "warning",
                "context.too-large",
                (
                    f"always-loaded policy is {metrics['always_loaded_chars']} characters; "
                    f"configured limit is {context_limit}"
                ),
                CONFIG_NAME,
            )
        )

    routes = config.get("routes", [])
    if not isinstance(routes, list):
        findings.append(Finding("error", "config.routes", "routes must be an array", CONFIG_NAME))
        routes = []
    route_ids: set[str] = set()
    has_default = False
    for route in routes:
        if not isinstance(route, dict):
            findings.append(Finding("error", "route.invalid", "each route must be an object", CONFIG_NAME))
            continue
        identifier = route.get("id")
        if not isinstance(identifier, str) or not identifier:
            findings.append(Finding("error", "route.id", "route id must be non-empty", CONFIG_NAME))
            continue
        if identifier in route_ids:
            findings.append(
                Finding("error", "route.duplicate", f"duplicate route id: {identifier}", CONFIG_NAME)
            )
        route_ids.add(identifier)
        has_default = has_default or identifier == "default"
        for key in ("terms", "paths", "read", "validation"):
            value = route.get(key, [])
            if not isinstance(value, list) or not all(isinstance(x, str) for x in value):
                findings.append(
                    Finding(
                        "error",
                        f"route.{key}",
                        f"route {identifier} field {key} must be an array of strings",
                        CONFIG_NAME,
                    )
                )
        for authority_id in route.get("read", []):
            if authority_id not in authorities:
                findings.append(
                    Finding(
                        "error",
                        "route.unknown-authority",
                        f"route {identifier} references unknown authority {authority_id}",
                        CONFIG_NAME,
                    )
                )
    metrics["route_count"] = len(route_ids)
    if routes and not has_default:
        findings.append(
            Finding("warning", "route.no-default", "no route named default is configured", CONFIG_NAME)
        )

    paragraph_owners: dict[str, list[str]] = {}
    paragraph_samples: dict[str, str] = {}
    for relative in checked_docs:
        path = root / relative
        if not path.is_file() or path.suffix.lower() != ".md":
            continue
        for normalized, sample in normalized_paragraphs(path, duplicate_min).items():
            paragraph_owners.setdefault(normalized, []).append(relative)
            paragraph_samples[normalized] = sample
    for normalized, owners in paragraph_owners.items():
        unique_owners = sorted(set(owners))
        if len(unique_owners) > 1:
            sample = paragraph_samples[normalized][:120]
            findings.append(
                Finding(
                    "warning",
                    "policy.duplicate",
                    f"same long policy paragraph appears in {', '.join(unique_owners)}: {sample!r}",
                )
            )

    tooling = config.get("tooling", {})
    if isinstance(tooling, dict):
        roots = tooling.get("roots", [])
        allowed = tooling.get("allowed", [])
        if isinstance(roots, list) and isinstance(allowed, list):
            for relative_root in roots:
                if not isinstance(relative_root, str):
                    continue
                directory = root / relative_root
                if not directory.exists():
                    continue
                unexpected = [
                    posix(path.relative_to(root))
                    for path in directory.rglob("*")
                    if path.is_file()
                    and not matches_allowed(posix(path.relative_to(root)), allowed)
                ]
                if unexpected:
                    preview = ", ".join(unexpected[:5])
                    suffix = f" (+{len(unexpected) - 5} more)" if len(unexpected) > 5 else ""
                    findings.append(
                        Finding(
                            "warning",
                            "tooling.pollution",
                            f"unexpected runtime/data files in tooling root: {preview}{suffix}",
                            relative_root,
                        )
                    )
        else:
            findings.append(
                Finding(
                    "error",
                    "config.tooling",
                    "tooling.roots and tooling.allowed must be arrays",
                    CONFIG_NAME,
                )
            )

    validation = config.get("validation", {})
    profile_ids: set[str] = set()
    if not isinstance(validation, dict):
        findings.append(
            Finding("error", "config.validation", "validation must be an object", CONFIG_NAME)
        )
        validation = {}
    profiles = validation.get("profiles", {})
    if not isinstance(profiles, dict):
        findings.append(
            Finding("error", "validation.profiles", "validation.profiles must be an object", CONFIG_NAME)
        )
        profiles = {}
    for profile_id, profile in profiles.items():
        profile_ids.add(str(profile_id))
        if not isinstance(profile, dict):
            findings.append(
                Finding(
                    "error",
                    "validation.profile",
                    f"validation profile {profile_id} must be an object",
                    CONFIG_NAME,
                )
            )
            continue
        extends = profile.get("extends", [])
        commands = profile.get("commands", [])
        if not isinstance(extends, list) or not all(isinstance(item, str) for item in extends):
            findings.append(
                Finding(
                    "error",
                    "validation.extends",
                    f"validation profile {profile_id} extends must be an array",
                    CONFIG_NAME,
                )
            )
        if not isinstance(commands, list):
            findings.append(
                Finding(
                    "error",
                    "validation.commands",
                    f"validation profile {profile_id} commands must be an array",
                    CONFIG_NAME,
                )
            )
            continue
        for index, entry in enumerate(commands):
            normalized = normalize_command(entry)
            if normalized is None:
                findings.append(
                    Finding(
                        "error",
                        "validation.command",
                        f"validation profile {profile_id} command {index} is invalid",
                        CONFIG_NAME,
                    )
                )
            elif not normalized[1]:
                findings.append(
                    Finding(
                        "warning",
                        "validation.proof-missing",
                        f"validation profile {profile_id} command {index} does not say what it proves",
                        CONFIG_NAME,
                    )
                )
    for profile_id, profile in profiles.items():
        if not isinstance(profile, dict):
            continue
        for parent in profile.get("extends", []):
            if parent not in profile_ids:
                findings.append(
                    Finding(
                        "error",
                        "validation.unknown-parent",
                        f"validation profile {profile_id} extends unknown profile {parent}",
                        CONFIG_NAME,
                    )
                )
    defaults = validation.get("default_profiles", [])
    if not isinstance(defaults, list) or not all(isinstance(item, str) for item in defaults):
        findings.append(
            Finding(
                "error",
                "validation.defaults",
                "validation.default_profiles must be an array",
                CONFIG_NAME,
            )
        )
        defaults = []
    for selected in [
        *defaults,
        *[
            profile
            for route in routes
            if isinstance(route, dict)
            for profile in route.get("validation", [])
        ],
    ]:
        if selected not in profile_ids:
            findings.append(
                Finding(
                    "error",
                    "validation.unknown-profile",
                    f"route/default references unknown validation profile {selected}",
                    CONFIG_NAME,
                )
            )
    for selected in profile_ids:
        try:
            expand_validation_profiles(config, [selected])
        except ValueError as exc:
            findings.append(Finding("error", "validation.graph", str(exc), CONFIG_NAME))

    development_interfaces = config.get("development_interfaces")
    if not isinstance(development_interfaces, list):
        findings.append(
            Finding(
                "error",
                "config.development-interfaces",
                "development_interfaces must be an array",
                CONFIG_NAME,
            )
        )
        development_interfaces = []
    interface_ids: set[str] = set()
    activation_flags: set[str] = set()
    for index, interface in enumerate(development_interfaces):
        if not isinstance(interface, dict):
            findings.append(
                Finding(
                    "error",
                    "development-interface.invalid",
                    f"development interface {index} must be an object",
                    CONFIG_NAME,
                )
            )
            continue
        identifier = interface.get("id")
        if not isinstance(identifier, str) or not identifier.strip():
            findings.append(
                Finding(
                    "error",
                    "development-interface.id",
                    f"development interface {index} needs a non-empty id",
                    CONFIG_NAME,
                )
            )
        elif identifier in interface_ids:
            findings.append(
                Finding(
                    "error",
                    "development-interface.duplicate",
                    f"duplicate development interface id {identifier}",
                    CONFIG_NAME,
                )
            )
        else:
            interface_ids.add(identifier)

        protocol = interface.get("protocol")
        if not isinstance(protocol, str) or not protocol.strip():
            findings.append(
                Finding(
                    "error",
                    "development-interface.protocol",
                    f"development interface {identifier or index} needs a protocol",
                    CONFIG_NAME,
                )
            )

        activation_flag = interface.get("activation_flag")
        if not isinstance(activation_flag, str) or not activation_flag.strip():
            findings.append(
                Finding(
                    "error",
                    "development-interface.activation-flag",
                    (
                        f"development interface {identifier or index} needs exactly one "
                        "non-empty activation_flag"
                    ),
                    CONFIG_NAME,
                )
            )
        elif activation_flag in activation_flags:
            findings.append(
                Finding(
                    "error",
                    "development-interface.duplicate-flag",
                    f"activation flag {activation_flag!r} is used more than once",
                    CONFIG_NAME,
                )
            )
        else:
            activation_flags.add(activation_flag)

        if interface.get("default_enabled") is not False:
            findings.append(
                Finding(
                    "error",
                    "development-interface.default-enabled",
                    (
                        f"development interface {identifier or index} must set "
                        "default_enabled to false"
                    ),
                    CONFIG_NAME,
                )
            )
        if not isinstance(interface.get("production_allowed"), bool):
            findings.append(
                Finding(
                    "error",
                    "development-interface.production-policy",
                    (
                        f"development interface {identifier or index} must explicitly set "
                        "production_allowed"
                    ),
                    CONFIG_NAME,
                )
            )

        guard_profiles = interface.get("guard_profiles")
        if (
            not isinstance(guard_profiles, list)
            or not guard_profiles
            or not all(isinstance(profile, str) and profile for profile in guard_profiles)
        ):
            findings.append(
                Finding(
                    "error",
                    "development-interface.guards",
                    (
                        f"development interface {identifier or index} needs one or more "
                        "guard_profiles"
                    ),
                    CONFIG_NAME,
                )
            )
        else:
            for guard_profile in guard_profiles:
                if guard_profile not in profile_ids:
                    findings.append(
                        Finding(
                            "error",
                            "development-interface.unknown-profile",
                            (
                                f"development interface {identifier or index} references "
                                f"unknown validation profile {guard_profile}"
                            ),
                            CONFIG_NAME,
                        )
                    )
    metrics["development_interface_count"] = len(interface_ids)

    adapters = config.get("adapters", {})
    if not isinstance(adapters, dict) or not isinstance(adapters.get("outputs", []), list):
        findings.append(
            Finding("error", "config.adapters", "adapters.outputs must be an array", CONFIG_NAME)
        )
    else:
        output_paths: set[str] = set()
        raw_outputs = adapters.get("outputs", [])
        for index, raw_output in enumerate(raw_outputs):
            if not isinstance(raw_output, dict):
                findings.append(
                    Finding(
                        "error",
                        "adapter.invalid",
                        f"adapter output {index} must be an object",
                        CONFIG_NAME,
                    )
                )
                continue
            kind = raw_output.get("kind")
            path = raw_output.get("path")
            if kind not in {"agents", "copilot"}:
                findings.append(
                    Finding(
                        "error",
                        "adapter.kind",
                        f"adapter output {index} has unknown kind {kind!r}",
                        CONFIG_NAME,
                    )
                )
            if not isinstance(path, str) or not path.strip():
                findings.append(
                    Finding(
                        "error",
                        "adapter.path",
                        f"adapter output {index} needs a non-empty path",
                        CONFIG_NAME,
                    )
                )
        for output in adapter_outputs(config):
            if output["path"] in output_paths:
                findings.append(
                    Finding(
                        "error",
                        "adapter.duplicate",
                        f"duplicate adapter output {output['path']}",
                        CONFIG_NAME,
                    )
                )
            output_paths.add(output["path"])
        findings.extend(generate_adapters(root, config, write=False, force=False))

    findings.extend(route_test_findings(config))

    rules = config.get("rules", [])
    if not isinstance(rules, list):
        findings.append(Finding("error", "config.rules", "rules must be an array", CONFIG_NAME))
        rules = []
    rule_ids: set[str] = set()
    for rule in rules:
        if not isinstance(rule, dict) or not isinstance(rule.get("id"), str):
            findings.append(Finding("error", "rule.invalid", "each rule needs an id", CONFIG_NAME))
            continue
        if rule["id"] in rule_ids:
            findings.append(
                Finding("error", "rule.duplicate", f"duplicate rule id {rule['id']}", CONFIG_NAME)
            )
        rule_ids.add(rule["id"])
        if rule.get("authority") not in authorities:
            findings.append(
                Finding(
                    "error",
                    "rule.authority",
                    f"rule {rule['id']} references unknown authority",
                    CONFIG_NAME,
                )
            )
        source = rule.get("source")
        if not isinstance(source, str) or not source.strip():
            findings.append(
                Finding(
                    "warning",
                    "rule.source",
                    f"rule {rule['id']} has no source citation",
                    CONFIG_NAME,
                )
            )
        else:
            source_path = source.split("#", 1)[0]
            authority = authorities.get(str(rule.get("authority")))
            authority_path = authority.get("path") if isinstance(authority, dict) else None
            if source_path != authority_path:
                findings.append(
                    Finding(
                        "error",
                        "rule.source-authority",
                        (
                            f"rule {rule['id']} source {source_path!r} does not match "
                            f"authority path {authority_path!r}"
                        ),
                        CONFIG_NAME,
                    )
                )
        guard = rule.get("guard")
        if guard and guard not in profile_ids:
            findings.append(
                Finding(
                    "error",
                    "rule.guard",
                    f"rule {rule['id']} references unknown validation profile {guard}",
                    CONFIG_NAME,
                )
            )

    evidence = config.get("evidence", {})
    if not isinstance(evidence, dict) or not isinstance(evidence.get("directory"), str):
        findings.append(
            Finding(
                "error",
                "config.evidence",
                "evidence.directory must be configured",
                CONFIG_NAME,
            )
        )
    else:
        try:
            project_path(root, evidence["directory"])
        except ValueError as exc:
            findings.append(Finding("error", "evidence.path", str(exc), CONFIG_NAME))

    coverage = coverage_report(config)
    metrics["coverage"] = coverage
    for key in (
        "unrouted_authorities",
        "untested_routes",
        "unused_validation_profiles",
        "unguarded_rules",
    ):
        values = coverage[key]
        if values:
            findings.append(
                Finding(
                    "warning",
                    f"coverage.{key.replace('_', '-')}",
                    f"{key.replace('_', ' ')}: {', '.join(values)}",
                    CONFIG_NAME,
                )
            )

    return findings, metrics


def route_details(config: dict[str, Any], task: str, paths: list[str]) -> dict[str, list[str]]:
    authorities = {
        item["id"]: item
        for item in config.get("authorities", [])
        if isinstance(item, dict) and isinstance(item.get("id"), str)
    }
    selected: list[str] = [
        item["id"]
        for item in authorities.values()
        if item.get("always") is True
    ]
    matched_routes: list[str] = []
    validation_profiles: list[str] = []
    task_lower = task.lower()
    non_default_matched = False
    for route in config.get("routes", []):
        if not isinstance(route, dict):
            continue
        identifier = str(route.get("id", ""))
        terms = [str(term).lower() for term in route.get("terms", [])]
        globs = [str(pattern) for pattern in route.get("paths", [])]
        term_match = any(term and term in task_lower for term in terms)
        path_match = any(
            fnmatch.fnmatchcase(posix(path), pattern)
            for path in paths
            for pattern in globs
        )
        matched = term_match or path_match
        if identifier == "default":
            continue
        if matched:
            non_default_matched = True
            matched_routes.append(identifier)
            selected.extend(str(item) for item in route.get("read", []))
            validation_profiles.extend(str(item) for item in route.get("validation", []))
    if not non_default_matched:
        for route in config.get("routes", []):
            if isinstance(route, dict) and route.get("id") == "default":
                matched_routes.append("default")
                selected.extend(str(item) for item in route.get("read", []))
                validation_profiles.extend(str(item) for item in route.get("validation", []))
                break
    documents: list[str] = []
    for identifier in dict.fromkeys(selected):
        authority = authorities.get(identifier)
        if authority and isinstance(authority.get("path"), str):
            documents.append(authority["path"])
    if not validation_profiles:
        validation_profiles.extend(
            str(item)
            for item in config.get("validation", {}).get("default_profiles", [])
        )
    return {
        "routes": list(dict.fromkeys(matched_routes)),
        "documents": documents,
        "validation_profiles": list(dict.fromkeys(validation_profiles)),
    }


def route_documents(root: Path, task: str, paths: list[str]) -> tuple[list[str], list[str]]:
    config, findings = load_config(root)
    if config is None:
        return [], [finding.message for finding in findings]
    details = route_details(config, task, paths)
    return details["documents"], details["routes"]


def render_adapter(config: dict[str, Any], kind: str) -> str:
    project = config.get("project", {})
    project_name = str(project.get("name", "Project")).strip() or "Project"
    authorities = [
        item
        for item in config.get("authorities", [])
        if isinstance(item, dict)
        and isinstance(item.get("path"), str)
        and isinstance(item.get("id"), str)
    ]
    if kind == "agents":
        return (
            f"{GENERATED_MARKER}\n"
            f"# {project_name} agent instructions\n\n"
            "Read [.github/copilot-instructions.md](.github/copilot-instructions.md).\n"
            f"Use [{CONFIG_NAME}]({CONFIG_NAME}) to load only the authorities routed for\n"
            "the current task and likely changed paths. Project-specific policy belongs\n"
            "in those authorities, not in this generated entrypoint.\n"
        )
    if kind != "copilot":
        raise ValueError(f"unknown adapter kind: {kind}")

    authority_lines = []
    for index, authority in enumerate(authorities, start=1):
        purpose = str(authority.get("purpose", authority["id"])).strip()
        authority_lines.append(
            f"{index}. [{purpose}](../{posix(authority['path'])})"
        )
    authority_text = "\n".join(authority_lines) or "1. The current user request."
    return (
        f"{GENERATED_MARKER}\n"
        f"# {project_name} agent brief\n\n"
        f"Task routing is defined by [`{CONFIG_NAME}`](../{CONFIG_NAME}). Match the\n"
        "request and likely changed paths, then read every returned authority\n"
        "completely. Do not load unrelated policy just in case.\n\n"
        "## Authority order\n\n"
        f"{authority_text}\n\n"
        "The user's current request controls the task. Lower authorities do not\n"
        "silently override higher ones.\n\n"
        "## Working contract\n\n"
        "- Inspect relevant implementation and version-control state before editing.\n"
        "- Preserve unrelated user changes.\n"
        "- Decide capability ownership before placing code or policy.\n"
        "- Make the smallest coherent change that achieves the requested outcome.\n"
        "- Validate in proportion to risk and report only current evidence.\n"
        "- Planned, incomplete, stale, or unrun work is not complete.\n"
    )


def adapter_outputs(config: dict[str, Any]) -> list[dict[str, str]]:
    adapters = config.get("adapters", {})
    outputs = adapters.get("outputs", []) if isinstance(adapters, dict) else []
    return [
        {"kind": str(item["kind"]), "path": str(item["path"])}
        for item in outputs
        if isinstance(item, dict) and "kind" in item and "path" in item
    ]


def generate_adapters(root: Path, config: dict[str, Any], write: bool, force: bool) -> list[Finding]:
    findings: list[Finding] = []
    for output in adapter_outputs(config):
        relative = output["path"]
        try:
            target = project_path(root, relative)
            expected = render_adapter(config, output["kind"])
        except ValueError as exc:
            findings.append(Finding("error", "adapter.invalid", str(exc), relative))
            continue
        current = target.read_text(encoding="utf-8") if target.exists() else None
        if current == expected:
            continue
        if not write:
            findings.append(
                Finding("error", "adapter.stale", "generated adapter is missing or stale", relative)
            )
            continue
        if current is not None and GENERATED_MARKER not in current and not force:
            findings.append(
                Finding(
                    "error",
                    "adapter.unmanaged",
                    "refusing to overwrite an unmanaged adapter without --force",
                    relative,
                )
            )
            continue
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(expected, encoding="utf-8")
        print(f"Generated {relative}")
    return findings


def normalize_command(entry: Any) -> tuple[str, str] | None:
    if isinstance(entry, str) and entry.strip():
        return entry.strip(), ""
    if not isinstance(entry, dict):
        return None
    command = entry.get("run")
    proves = entry.get("proves")
    if not isinstance(command, str) or not command.strip():
        return None
    if not isinstance(proves, str):
        proves = ""
    return command.strip(), proves.strip()


def expand_validation_profiles(config: dict[str, Any], selected: list[str]) -> tuple[list[str], list[tuple[str, str]]]:
    profiles = config.get("validation", {}).get("profiles", {})
    ordered_profiles: list[str] = []
    commands: list[tuple[str, str]] = []
    visiting: set[str] = set()

    def visit(name: str) -> None:
        if name in ordered_profiles:
            return
        if name in visiting:
            raise ValueError(f"validation profile cycle at {name}")
        profile = profiles.get(name)
        if not isinstance(profile, dict):
            raise ValueError(f"unknown validation profile: {name}")
        visiting.add(name)
        for parent in profile.get("extends", []):
            visit(str(parent))
        visiting.remove(name)
        ordered_profiles.append(name)
        for entry in profile.get("commands", []):
            normalized = normalize_command(entry)
            if normalized and normalized not in commands:
                commands.append(normalized)

    for profile_name in selected:
        visit(profile_name)
    return ordered_profiles, commands


def git_state(root: Path) -> dict[str, Any]:
    def capture(args: list[str]) -> str | None:
        result = subprocess.run(
            ["git", *args],
            cwd=root,
            text=True,
            capture_output=True,
            check=False,
        )
        return result.stdout.strip() if result.returncode == 0 else None

    revision = capture(["rev-parse", "HEAD"])
    status = capture(["status", "--porcelain=v1"])
    return {
        "revision": revision,
        "dirty": bool(status) if status is not None else None,
        "status_sha256": (
            hashlib.sha256(status.encode("utf-8")).hexdigest()
            if status is not None
            else None
        ),
    }


def write_receipt(root: Path, config: dict[str, Any], payload: dict[str, Any]) -> Path:
    evidence = config.get("evidence", {})
    relative_dir = (
        str(evidence.get("directory", ".agent-evidence"))
        if isinstance(evidence, dict)
        else ".agent-evidence"
    )
    directory = project_path(root, relative_dir)
    directory.mkdir(parents=True, exist_ok=True)
    stamp = datetime.now(timezone.utc).strftime("%Y%m%dT%H%M%SZ")
    revision = payload.get("vcs", {}).get("revision")
    suffix = str(revision)[:8] if revision else "no-vcs"
    target = directory / f"{stamp}-{suffix}.json"
    counter = 1
    while target.exists():
        target = directory / f"{stamp}-{suffix}-{counter}.json"
        counter += 1
    temporary = target.with_suffix(".tmp")
    temporary.write_text(json.dumps(payload, indent=2) + "\n", encoding="utf-8")
    temporary.replace(target)
    return target


def verify(
    root: Path,
    config: dict[str, Any],
    task: str,
    paths: list[str],
    claim: str,
    requested_profiles: list[str],
    create_receipt: bool,
) -> tuple[int, dict[str, Any], Path | None]:
    details = route_details(config, task, paths)
    selected = requested_profiles or details["validation_profiles"]
    profiles, commands = expand_validation_profiles(config, selected)
    if not commands:
        raise ValueError("selected validation profiles contain no commands")
    results: list[dict[str, Any]] = []
    for command, proves in commands:
        print(f"> {command}", flush=True)
        started = time.perf_counter()
        result = subprocess.run(
            command,
            cwd=root,
            shell=True,
            text=True,
            capture_output=True,
            check=False,
        )
        duration_ms = round((time.perf_counter() - started) * 1000, 3)
        if result.stdout:
            print(result.stdout, end="" if result.stdout.endswith("\n") else "\n")
        if result.stderr:
            print(result.stderr, file=sys.stderr, end="" if result.stderr.endswith("\n") else "\n")
        results.append(
            {
                "run": command,
                "proves": proves,
                "exit_code": result.returncode,
                "duration_ms": duration_ms,
                "stdout_sha256": hashlib.sha256(result.stdout.encode("utf-8")).hexdigest(),
                "stderr_sha256": hashlib.sha256(result.stderr.encode("utf-8")).hexdigest(),
            }
        )
    vcs = git_state(root)
    config_bytes = (root / CONFIG_NAME).read_bytes()
    payload = {
        "schema": "project-agent-toolkit.evidence.v1",
        "created_at": datetime.now(timezone.utc).isoformat(),
        "project_root": str(root),
        "governance_sha256": hashlib.sha256(config_bytes).hexdigest(),
        "vcs": vcs,
        "task": task,
        "paths": paths,
        "claim": claim,
        "routes": details["routes"],
        "documents": details["documents"],
        "profiles": profiles,
        "results": results,
        "passed": all(item["exit_code"] == 0 for item in results),
    }
    receipt = write_receipt(root, config, payload) if create_receipt else None
    return (0 if payload["passed"] else 1), payload, receipt


def route_test_findings(config: dict[str, Any]) -> list[Finding]:
    findings: list[Finding] = []
    tests = config.get("route_tests", [])
    if not isinstance(tests, list):
        return [Finding("error", "route-tests.invalid", "route_tests must be an array", CONFIG_NAME)]
    for index, test in enumerate(tests):
        if not isinstance(test, dict):
            findings.append(
                Finding("error", "route-test.invalid", f"route test {index} must be an object", CONFIG_NAME)
            )
            continue
        identifier = str(test.get("id", index))
        task = str(test.get("task", ""))
        paths = test.get("paths", [])
        if not isinstance(paths, list) or not all(isinstance(path, str) for path in paths):
            findings.append(
                Finding("error", "route-test.paths", f"route test {identifier} paths are invalid", CONFIG_NAME)
            )
            continue
        actual = route_details(config, task, paths)
        for field, actual_key in (
            ("expect_routes", "routes"),
            ("expect_documents", "documents"),
            ("expect_validation_profiles", "validation_profiles"),
        ):
            expected = test.get(field)
            if expected is None:
                continue
            if not isinstance(expected, list) or not all(isinstance(item, str) for item in expected):
                findings.append(
                    Finding(
                        "error",
                        "route-test.expectation",
                        f"route test {identifier} field {field} is invalid",
                        CONFIG_NAME,
                    )
                )
                continue
            if actual[actual_key] != expected:
                findings.append(
                    Finding(
                        "error",
                        "route-test.failed",
                        (
                            f"{identifier} expected {actual_key}={expected!r}, "
                            f"got {actual[actual_key]!r}"
                        ),
                        CONFIG_NAME,
                    )
                )
    return findings


def coverage_report(config: dict[str, Any]) -> dict[str, Any]:
    authorities = {
        str(item.get("id"))
        for item in config.get("authorities", [])
        if isinstance(item, dict) and item.get("id")
    }
    routes = [
        item
        for item in config.get("routes", [])
        if isinstance(item, dict) and isinstance(item.get("id"), str)
    ]
    routed_authorities = {
        str(authority)
        for route in routes
        for authority in route.get("read", [])
    }
    tests = [
        item
        for item in config.get("route_tests", [])
        if isinstance(item, dict)
    ]
    tested_routes = {
        route
        for test in tests
        for route in test.get("expect_routes", [])
    }
    profiles = set(config.get("validation", {}).get("profiles", {}).keys())
    referenced_profiles = {
        str(profile)
        for route in routes
        for profile in route.get("validation", [])
    }
    referenced_profiles.update(
        str(profile)
        for profile in config.get("validation", {}).get("default_profiles", [])
    )
    referenced_profiles.update(
        str(rule.get("guard"))
        for rule in config.get("rules", [])
        if isinstance(rule, dict) and rule.get("guard")
    )
    referenced_profiles.update(
        str(profile)
        for interface in config.get("development_interfaces", [])
        if isinstance(interface, dict)
        for profile in interface.get("guard_profiles", [])
    )
    unguarded_rules = [
        str(rule.get("id", "<unnamed>"))
        for rule in config.get("rules", [])
        if isinstance(rule, dict) and not rule.get("guard")
    ]
    gaps = {
        "unrouted_authorities": sorted(authorities - routed_authorities),
        "untested_routes": sorted(
            str(route["id"])
            for route in routes
            if route["id"] != "default" and route["id"] not in tested_routes
        ),
        "unused_validation_profiles": sorted(profiles - referenced_profiles),
        "unguarded_rules": sorted(unguarded_rules),
        "failing_route_tests": [
            asdict(finding)
            for finding in route_test_findings(config)
            if finding.severity == "error"
        ],
    }
    gaps["complete"] = not any(value for key, value in gaps.items() if key != "complete")
    return gaps


def migrate_config(config: dict[str, Any]) -> dict[str, Any]:
    version = config.get("version")
    if version == CURRENT_VERSION:
        return config
    if version not in {1, 2}:
        raise ValueError(f"cannot migrate configuration version {version!r}")
    migrated = json.loads(json.dumps(config))
    if version == 1:
        migrated["version"] = 2
        migrated.setdefault("project", {"name": "Project"})
        migrated.setdefault(
            "adapters",
            {
                "outputs": [
                    {"kind": "agents", "path": "AGENTS.md"},
                    {"kind": "copilot", "path": ".github/copilot-instructions.md"},
                ]
            },
        )
        old_commands = migrated.get("validation", {}).pop("commands", [])
        validation = migrated.setdefault("validation", {})
        validation.setdefault(
            "profiles",
            {
                "fast": {
                    "commands": [
                        {
                            "run": command,
                            "proves": "Project-configured fast validation",
                        }
                        for command in old_commands
                    ]
                }
            },
        )
        validation.setdefault("default_profiles", ["fast"])
        route_tests = []
        for route in migrated.get("routes", []):
            if not isinstance(route, dict) or not route.get("id"):
                continue
            route.setdefault("validation", ["fast"])
            terms = route.get("terms", [])
            paths = route.get("paths", [])
            test_task = str(terms[0]) if terms else ""
            test_paths = [str(paths[0])] if paths and route["id"] != "default" else []
            route_tests.append(
                {
                    "id": f"{route['id']}-route",
                    "task": test_task,
                    "paths": test_paths,
                }
            )
        for route_test in route_tests:
            actual = route_details(
                migrated,
                str(route_test["task"]),
                [str(path) for path in route_test["paths"]],
            )
            route_test["expect_routes"] = actual["routes"]
            route_test["expect_documents"] = actual["documents"]
            route_test["expect_validation_profiles"] = actual["validation_profiles"]
        migrated.setdefault("route_tests", route_tests)
        migrated.setdefault("rules", [])
        migrated.setdefault("evidence", {"directory": ".agent-evidence"})

    migrated["version"] = CURRENT_VERSION
    migrated.setdefault("development_interfaces", [])
    return migrated


def print_audit(findings: list[Finding], metrics: dict[str, Any], as_json: bool) -> None:
    if as_json:
        print(
            json.dumps(
                {
                    "metrics": metrics,
                    "findings": [asdict(finding) for finding in findings],
                },
                indent=2,
            )
        )
        return
    errors = sum(f.severity == "error" for f in findings)
    warnings = sum(f.severity == "warning" for f in findings)
    print(
        f"Agent governance audit: {errors} error(s), {warnings} warning(s); "
        f"always-loaded {metrics.get('always_loaded_chars', 0)} chars"
    )
    for finding in findings:
        location = f" [{finding.path}]" if finding.path else ""
        print(f"{finding.severity.upper():7} {finding.code}{location}: {finding.message}")


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description="Bootstrap, generate, route, verify, and audit project agent governance."
    )
    subparsers = parser.add_subparsers(dest="command", required=True)

    init_parser = subparsers.add_parser("init", help="add governance files without overwriting")
    init_parser.add_argument("--root", type=Path, default=Path.cwd())
    init_parser.add_argument("--profile", choices=("minimal", "full"), default="minimal")
    init_parser.add_argument("--force", action="store_true")

    for name in ("audit", "check"):
        audit_parser = subparsers.add_parser(name, help=f"{name} governance configuration")
        audit_parser.add_argument("--root", type=Path, default=Path.cwd())
        audit_parser.add_argument("--json", action="store_true")

    route_parser = subparsers.add_parser("route", help="print task-scoped authority documents")
    route_parser.add_argument("--root", type=Path, default=Path.cwd())
    route_parser.add_argument("--task", default="")
    route_parser.add_argument("--path", action="append", default=[])
    route_parser.add_argument("--json", action="store_true")

    route_test_parser = subparsers.add_parser("route-test", help="run configured routing contracts")
    route_test_parser.add_argument("--root", type=Path, default=Path.cwd())
    route_test_parser.add_argument("--json", action="store_true")

    generate_parser = subparsers.add_parser("generate", help="check or write managed agent adapters")
    generate_parser.add_argument("--root", type=Path, default=Path.cwd())
    generate_parser.add_argument("--write", action="store_true")
    generate_parser.add_argument("--force", action="store_true")

    verify_parser = subparsers.add_parser("verify", help="select and run validation profiles")
    verify_parser.add_argument("--root", type=Path, default=Path.cwd())
    verify_parser.add_argument("--task", default="")
    verify_parser.add_argument("--path", action="append", default=[])
    verify_parser.add_argument("--claim", default="")
    verify_parser.add_argument("--profile", action="append", default=[])
    verify_parser.add_argument("--no-receipt", action="store_true")
    verify_parser.add_argument("--json", action="store_true")

    coverage_parser = subparsers.add_parser("coverage", help="report governance coverage gaps")
    coverage_parser.add_argument("--root", type=Path, default=Path.cwd())
    coverage_parser.add_argument("--json", action="store_true")
    coverage_parser.add_argument("--strict", action="store_true")

    upgrade_parser = subparsers.add_parser("upgrade", help="migrate governance config safely")
    upgrade_parser.add_argument("--root", type=Path, default=Path.cwd())
    upgrade_parser.add_argument("--write", action="store_true")
    upgrade_parser.add_argument("--json", action="store_true")
    return parser


def main(argv: list[str] | None = None) -> int:
    args = build_parser().parse_args(argv)
    root = args.root.expanduser().resolve()
    if args.command == "init":
        return initialize(root, args.profile, args.force)
    if args.command == "route":
        config, config_findings = load_config(root)
        if config is None:
            for finding in config_findings:
                print(f"ERROR {finding.message}", file=sys.stderr)
            return 1
        details = route_details(config, args.task, args.path)
        if args.json:
            print(json.dumps(details, indent=2))
        else:
            print(
                f"Matched routes: "
                f"{', '.join(details['routes']) if details['routes'] else 'none'}"
            )
            for document in details["documents"]:
                print(document)
            if details["validation_profiles"]:
                print(f"Validation: {', '.join(details['validation_profiles'])}")
        return 0 if details["documents"] else 1
    if args.command == "route-test":
        config, config_findings = load_config(root)
        if config is None:
            for finding in config_findings:
                print(f"ERROR {finding.message}", file=sys.stderr)
            return 1
        findings = route_test_findings(config)
        if args.json:
            print(json.dumps([asdict(finding) for finding in findings], indent=2))
        elif findings:
            for finding in findings:
                print(f"{finding.severity.upper()} {finding.code}: {finding.message}")
        else:
            print(f"route-test: OK ({len(config.get('route_tests', []))} contract(s))")
        return 1 if any(finding.severity == "error" for finding in findings) else 0
    if args.command == "generate":
        config, config_findings = load_config(root)
        if config is None:
            for finding in config_findings:
                print(f"ERROR {finding.message}", file=sys.stderr)
            return 1
        findings = generate_adapters(root, config, args.write, args.force)
        for finding in findings:
            print(
                f"{finding.severity.upper()} {finding.code}: {finding.message}",
                file=sys.stderr,
            )
        if not findings:
            print("generate: OK")
        return 1 if findings else 0
    if args.command == "verify":
        config, config_findings = load_config(root)
        if config is None:
            for finding in config_findings:
                print(f"ERROR {finding.message}", file=sys.stderr)
            return 1
        try:
            status, payload, receipt = verify(
                root,
                config,
                args.task,
                args.path,
                args.claim,
                args.profile,
                not args.no_receipt,
            )
        except ValueError as exc:
            print(f"verify: {exc}", file=sys.stderr)
            return 1
        if args.json:
            print(json.dumps({"receipt": str(receipt) if receipt else None, **payload}, indent=2))
        elif receipt:
            print(f"Evidence receipt: {receipt}")
        return status
    if args.command == "coverage":
        config, config_findings = load_config(root)
        if config is None:
            for finding in config_findings:
                print(f"ERROR {finding.message}", file=sys.stderr)
            return 1
        report = coverage_report(config)
        if args.json:
            print(json.dumps(report, indent=2))
        else:
            print(f"Governance coverage: {'complete' if report['complete'] else 'gaps found'}")
            for key, value in report.items():
                if key != "complete" and value:
                    print(f"  {key}: {value}")
        return 1 if args.strict and not report["complete"] else 0
    if args.command == "upgrade":
        config, config_findings = load_config(root)
        if config is None:
            for finding in config_findings:
                print(f"ERROR {finding.message}", file=sys.stderr)
            return 1
        try:
            migrated = migrate_config(config)
        except ValueError as exc:
            print(f"upgrade: {exc}", file=sys.stderr)
            return 1
        changed = migrated != config
        if args.json or not args.write:
            print(json.dumps(migrated, indent=2))
        if args.write and changed:
            target = root / CONFIG_NAME
            temporary = target.with_suffix(".tmp")
            temporary.write_text(json.dumps(migrated, indent=2) + "\n", encoding="utf-8")
            temporary.replace(target)
            print(f"Upgraded {CONFIG_NAME} to version {CURRENT_VERSION}")
        elif not changed:
            print(f"upgrade: already at version {CURRENT_VERSION}")
        return 0

    findings, metrics = audit(root)
    print_audit(findings, metrics, args.json)
    has_errors = any(finding.severity == "error" for finding in findings)
    has_warnings = any(finding.severity == "warning" for finding in findings)
    if args.command == "check":
        return 1 if has_errors or has_warnings else 0
    return 1 if has_errors else 0


if __name__ == "__main__":
    raise SystemExit(main())
